### PR TITLE
Implement mode for dangling ends resembling ViennaRNA's -d2

### PR DESCRIPTION
**Pull request by s-will**
Hi @IanWark, hi @HosnaJabbari,

this branch adds support for "-d2" type handling of dangling ends. Currently this works only for Sparse_CCJ---I didn't implement this for all functions of the simfold lib, (almost) only what's used by CCJ.

Currently, the dangle mode is controlled by a DEFINE in CMakeLists.txt, which was easiest to implement---in the long run, a command line option would be more convenient, of course.

As for testing, I could reproduce the CCJ energy with ViennaRNA for the following example:
SparseCCJ GGGGCCGGGGAACCCCAAAGGGCCCAAAGGGACCCUAAGGCCCC
(((((((((....)))..(((((((...))).))))..)))))) -17.21
using 
RNAeval -P ../sparse_ccj_parameter.viennarna -d2

@IanWark, could you please have a second look at this and merge.

### CODE REVIEW

**Comment by IanWark** [comment]
Hi @s-will,

I ran CCJ with dangle mode on and ./RNAfold -P sparse_ccj_parameter.viennarna on the HotKnots pseudoknot-free dataset (which has been uploaded to github under Datasets) and compared the output. I have been told that the results should be the exactly the same for these pseudoknot-free sequences and while many are the same, unfortunately many are different. Often the main difference is the inclusion of pseduoknotted structures but there are some that are both psuedoknot-free that are different. I double checked to make sure that I did remember to compile with dangle mode, so it is not that.

I have attached the output of my comparison script but it may be a little difficult to read so I will also just paste some test cases below with the output.
[compare_output.txt](https://github.com/HosnaJabbari/CCJ/files/1312082/compare_output.txt)

Also RNAfold's output files sometimes have ( -5.0) and sometimes have (-5.0) which made it more difficult to parse so I'm not sure if that's an issue whoever maintains it is away of.

CRW_00628
AAACACUUGCAUGUUUUGCCGCAGCAACUCUG
......((((.(((......)))))))..... ( -3.82)  -- RNAfold
(((((..[[[.)))))(((.]]])))......  -4.02    -- CCJ

CRW_00659
auggguGGUUUUCCAUCAGCAUUACCCAACACAGCUUUCAAGCUAGUA
.(((((.(((.......)))...)))))....((((....)))).... ( -6.53)
.((((((((...........))))))))..((((((([.))))).))]  -8.00

SRP_00381
CCGAGCUCUGUAGCGAGUGCUUGUAACCCGAGCGGGGGC
.(((((.((......)).)))))...(((....)))... ( -6.95)
....((((......))))(((([[..[[[))))]]].]]  -7.16

PDB_01071
GGCCAUCUUGCUCUUCGGAGGAUUUGGCC
(((((...(.(((....))).)..))))) ( -8.71)
(((((.....(((....)))....)))))  -9.15

PDB_00073
GCCGAGUAGUGUUGGGUCGCGAAAGGC
(((...(.(((......))).)..))) ( -2.75)
(((.....(((......)))....)))  -4.22

CRW_00697
ACUCUCUAAAUUGUAAAAUUUCCUUUGGAGGGA
.(((((((((..(........).))))))))). ( -5.28)
.(((((((((.............))))))))).  -6.22

CRW_00659
auggguGGUUUUCCAUCAGCAUUACCCAACACAGCUUUCAAGCUAGUA
.(((((.(((.......)))...)))))....((((....)))).... ( -6.53)
.((((((((...........))))))))..((((((([.))))).))]  -8.00

CRW_00672
UAUGACUCAACCUUUUGAGGGUCAUG
.(((((((..(.....).))))))). ( -3.94)
.(((((((..........))))))).  -5.39

ASE_00400
AGGUACCUGGCAACAGGUAUCCCAGAUGAAUGACCAUUACCCCAACCAUCUGAUUGGGGG
.((((((((....))))))))...((((......)))).((((((........)))))). (-16.33)
.((((((((....)))))))).((((((...........[[[[[[.)))))).]]]]]].  -18.29

ASE_00374
AGGCCGCCGGUGACGGCGGUCCCAGAUGAAUGAUUGCCACAGAUUAACUUCUGG
.((((((((....))))))))(((((.(..(((((......))))).).))))) (-16.35)
.((((((((....))))))))(((((....(((((......)))))...)))))  -16.67

SPR_00061
UCCCUGGUGGUCUAGUGGUUAGGAUUCGGCGCUCUCACCGCCGCGGCCCGGGUUCGAUUCCCGGUCAGGGAACCA
((((((((((((..(((((..(((........))).)))))...))))((((.......)))))))))))).... (-19.35)
(((((((.(((((..[[[[..)))))[[[[[.......]]]]]....{{{{{.......}}}}})))))))]]]]  -19.57

ASE_00090
AACCGGUCGGCAACGGCCGGUCCAGAUGGAUGGUCGCCACUGCGCGAGAGCGCGGUa
.((((((((....)))))))).....(((.......)))((((((....)))))).. (-19.43)
.((((((((....))))))))(((..[[[.)))...]]][[[[[[....]]]]]]..  -19.67

SRP_00381_version2
UGGGUCUAGUGCUACAAACUGUGGACCACCCAUUCCAAGUUGCGUAGUGGGUUUCGGAUGCCUUGGCGAAAGCUUUGCAUCCCAACACUAAAGUGGCGGACAUUGCGUGAGGCUGGCUUCAUAGAGCAGCGAGUACCGCCCGCCACCAGCGGUGGAAGGAUAAUGAGUCGCUAUGCUAUAGGCCCA
((((((((........((((.((((........))))))))(((((((((.....((((((...(((....)))..))))))...((((...(((((((.....(((....(((.(((.........))).)))..))))))))))....)))).............)))))))))..)))))))) (-43.62)
..((((((((.......)))..)))))((((((([[[[[..[[[[)))))))((((.]]]]]]]]]))))(((((((([[[[...[[[[...[[[[[[[.[...[[))))))))(((((.((((...(((((]]...].]]]]]]]....]]]]...]]]]......)))))...)))))))))..  -47.30

Arabidopsis
UUACUUACCUGGACGGGGUCAACUUGUGAUCAAUAAGACGAGUGGCCUAGGCUAGUGACCUCCAUUGCACAUAACGGAGGGGUGCUUAGCUUAAGGUCUCCCCAAGUGGGAGAGCCUGCGUCAUUAUUUGUGGCAGAGGGGGCCUGCGUUCGCGCGGUCCCUAC
.......(((....((((((...(((....)))...)))....((((((((((((((.(((((.(((....))).)))))..))).)))))).)))))..)))..(((((....)))))(((((.....)))))..)))(((.(((((....))))).)))... (-39.70)
..............((((...((((((..........))))))[[[[[[[[[[[[[[.[[[[[............]]]]]..]]].]]]]]].]]]]].))))..(((((....)))))(((((.....))))).(([[[[[[[.[[[[))]]]]]]]]]]]..  -42.26


I looked over the code itself quickly and it looked fine enough to me, though I didn't know what I was looking for. Let me know if you need anything else.

Ian Wark

**Comment by s-will** [comment]
Hi Ian,

when comparing the energies of CCJ's mfe structures to RNAeval, there is one little catch: RNAeval cannot score pseudoknots. This means that we cannot compare the energies of pseudoknotted structures (like in your example).
Everything would be fine, if we could reproduce the energies of all the pk-free structures mfe structures predicted by CCJ. Moreover, it is really sufficient to reproduce the energies using RNAeval---no need to run RNAfold.


Still, there are cases like

PDB_01071
GGCCAUCUUGCUCUUCGGAGGAUUUGGCC
(((((...(.(((....))).)..))))) ( -8.71)
(((((.....(((....)))....))))) -9.15

where RNAfold predicts isolated base pairs, which I cannot explain. These cases show that we still have differences in the energy functions:(.  Remarkably, at least in this case, no dangling end terms contribute to the total energy.
btw, I could confirm the differences.


Could you include the PK test in your script and produce the list of negative and positive examples. Maybe, we get some idea from this.



PS: You are right that parsing the output of RNAfold can be annoying. If you are using Python (or Perl) it is actually easier to use the bindings instead of system calls to the binaries. For example:

import RNA
energy = RNA.energy_of_struct(sequence,structure)

**Comment by IanWark** [comment]
Okay, so I've got the script changed and everything is ready but I realized that if I am using the bindings I don't know how to make it use the "sparse_ccj_parameter.viennarna" file.

I found the RNAlib reference manual and am looking through it now but having a bit of trouble knowing where to look.

Thanks

**Comment by IanWark** [comment]
Also, the RNAlib-2.4.1 reference manual says of the energy_of_struct function "This function is deprecated, use energy_of_structure instead!". The energy_of_structure function says "use vrna_eval_structure or vrna_eval_structure_verbose instead!". 

So should I use vrna_eval_stucture (or I think eval_structure for scripting interface)? If there is some kind of small difference in the actual answer I don't want go ahead and do that without checking with you first.

**Comment by s-will** [comment]
eval_structure has the advantage of supporting the new 'object-oriented' interface---currently one can use both.
For using the parameter file, there is a function read_parameter_file, which /should/ work (I didn't try this yet). Otherwise, feel free to go on using the system call---whether you use the bindings or call to RNAeval does not matter for the results.

**Comment by IanWark** [comment]
Here is the full output of comparing RNAeval and CCJ.
[CCJ_RNAeval_output.txt](https://github.com/HosnaJabbari/CCJ/files/1318326/CCJ_RNAeval_output.txt)

In this case you should probably be able to just look at the full output for examples. However I noticed a few cases that look quite similar yet have varying success. Hopefully this should help provide some insight. 

CRW_00650.result - YES: Energies are equal!
RNA: -3.99 CCJ: -3.99
Sequence: UUCCGUUAACACACCUAGCGGAU
Structure: .(((((((.......))))))).

CRW_00672.result - NO: Energies not equal!
RNA: -1.77 CCJ: -5.39
Sequence: UAUGACUCAACCUUUUGAGGGUCAUG
Structure: .(((((((..........))))))).


SRP_00236.result - YES: Energies are equal!
RNA: -4.64 CCJ: -4.64
Sequence: GUUGUGGCGAGCGCUUGUGAUCCAAGUGACUGGGAG
Structure: .......(.((((((((.....)))))).)).)...

SRP_00247.result - YES: Energies are equal!
RNA: -8.06 CCJ: -8.06
Sequence: GCUGGGAGUCGUGGCGUACUCCUGUCAUCCGGCG
Structure: ((((((.(.((.((......)))).).)))))).


CRW_00154.result - NO: Energies not equal!
RNA: -32.22 CCJ: -35.28
Sequence: CGCCCGUCACGUCAUGAAAGUCGGUAACACCCGAAGCCAGUGGCCUAACCCUCGGGAGGGAGCUGUCCAAGGUGGGAUCGGCGAUUGGGACGAAGUCGUAACAAGGUAGCCGUACCGGAAGGUGCGGCUGG
Structure: ....((.(.((((......((((((..((((....(.((((..(((..((....)))))..)))).)...))))..))))))......))))..).))........((((((((((....)))))))))).

CRW_00257.result - NO: Energies not equal!
RNA: -37.81 CCJ: -39.38
Sequence: CGCCCGUCACACCAUGGGAGUGGGCUGCAAAAGAAGCAGGUAGUUUAACCUUCGGGAGGACGCUUGCCACUUUGUGGUUCAUGACUGGGGUGAAGUCGUAACAAGGUAGCGCUAGGGGAACCUGGCGCUGG
Structure: ....((.(.((((.(((..((((((((((((....((((((.((((..((....)).))))))))))...))))))))))))..))).))))..).))........((((((((((....)))))))))).

CRW_00272.result - YES: Energies are equal!
RNA: -35.95 CCJ: -35.95
Sequence: CGCCCGUCACACCACGGGAGUCGGCCAUGCCGAAGUCGUUACCCUAACCAUUUCGGAGGGGGAUGCCUAAGGCAGGGCUGGUGACUGGGGUGAAGUCGUAACAAGGUAGCCGUACUGGAAGGUGUGGCUGG
Structure: ....((.(.((((.(((..(((((((.((((..((.((((.((((..((.....)))))).)))).))..)))).)))))))..))).))))..).))........((((((((((....)))))))))).

CRW_00285.result - YES: Energies are equal!
RNA: -37.91 CCJ: -37.91
Sequence: CGCCCGUCACACCACGGGAGCUGGCUAUGCCCAAAGUCGUUACCCCAACCGUUUGGAGGGGGAUGCCUAAGGCAGAGCUAGUGACUGGGGUGAAGUCGUAACAAGGUAGCCGUACUGGAAGGUGCGGCUGG
Structure: ....((.(.((((.(((..(((((((.((((...((.((((.((((..((....)).)))))))).))..)))).)))))))..))).))))..).))........((((((((((....)))))))))).


PDB_00049.result - YES: Energies are equal!
RNA: -6.68 CCJ: -6.68
Sequence: GGCGAAGUCGAAAGAUGGCGCC
Structure: ((((..(((....)))..))))

PDB_00073.result - NO: Energies not equal!
RNA: -2.72 CCJ: -4.22
Sequence: GCCGAGUAGUGUUGGGUCGCGAAAGGC
Structure: (((.....(((......)))....)))

**Comment by IanWark** [comment]
I was looking at the hairpin loop energy of RNAeval and CCJ based on the UAUGACUCAACCUUUUGAGGGUCAUG example you had in your email.

The hairpin was size 10.
RNAeval had energy 606 and CCJ had energy 244.

Both of them were composed entirely of size_penalty + mismatch_energy. The mismatch_energy was the same for both, -44,  but the penalty by size was different (CCJ had 288, RNAeval had 650).

I looked through the code for RNAeval and when size of hairpin is <= 30, it just reads the hairpin parameter given to it. CCJ does essentially the same thing, but only when the size of hairpin is <= 9. Instead, what it was doing was:

                    penalty30 = hairpin_penalty_by_size[9];
                    logval = log (1.0*size/9);
                    penalty =  (penalty30 + 100.0*misc.param_greater30 * logval);

If CCJ instead only does that when size <= 30, it returns the exact same energy for the hairpin. In this case, it changes the predicted structure, which when ran in RNAeval, results in the exact same energy.

CCJ
Seq: UAUGACUCAACCUUUUGAGGGUCAUG
RES: .(((((((..(.....).))))))).  -3.94

RNAeval
UAUGACUCAACCUUUUGAGGGUCAUG
.(((((((..(.....).))))))).
 energy =  -3.94 kcal/mol

However, if I instead change RNAeval to size <= 9, it does not match CCJ's result - it becomes 652 instead of 650. This is because ViennaRNA's calculation for when size > 9 is:

                    energy = P->hairpin[30] + (int)(P->lxc * log((size) / 30.));

So, what do you think is the best course of action here? Should we make it so when dangle mode is on we also change CCJ's MAXLOOP_H from 9 to 30, as well as its calculation when size > end to match ViennaRNA's? Or should we have another separate argument saying make hairpin calculations more like ViennaRNA? Or should we be changing the ViennaRNA we're using to match CCJ? 

Ian

**Comment by s-will** [comment]
Hi @IanWark, this is some time ago, so I lost track: did we come to a conclusion here? was this ever merged with the master? Can we close the PR?

**Pull request closed without merging**
